"""
Mathpix OCR backend.
Reads pre-existing .docx or .txt OCR output produced by the Mathpix service
and wraps it as an OCRPageResult for use in the extraction pipeline.
"""

from pathlib import Path

from mudidi.ocr.base import OCRBackend
from mudidi.schemas.ocr_result import OCRPageResult
from mudidi.utils.io import read_docx_text, read_text_file


class MathpixBackend(OCRBackend):
    """
    Loads Mathpix OCR output (DOCX or plain text) as an OCRPageResult.
    No network call is made; this backend reads files that were already
    generated by the Mathpix service and saved to disk.
    """

    @property
    def name(self) -> str:
        return "mathpix"

    @property
    def requires_api_key(self) -> bool:
        return False  # reading local files only

    @property
    def supports_layout_analysis(self) -> bool:
        return True  # Mathpix includes layout information in its output

    @property
    def is_open_source(self) -> bool:
        return False

    def run(self, image_path: str, ocr_file: str = None, **kwargs) -> OCRPageResult:
        """
        Load Mathpix OCR output from a .docx or .txt file.

        Args:
            image_path: Path to the original dictionary page image (used as source reference).
            ocr_file: Path to the Mathpix .docx or .txt output file.

        Returns:
            OCRPageResult with raw_text populated.

        Raises:
            ValueError: If ocr_file is not provided or does not exist.
        """
        if not ocr_file:
            raise ValueError("MathpixBackend.run() requires an 'ocr_file' argument.")

        ocr_path = Path(ocr_file)
        if not ocr_path.exists():
            raise ValueError(f"Mathpix OCR file not found: {ocr_file}")

        if ocr_path.suffix.lower() == ".docx":
            text = read_docx_text(str(ocr_path))
        else:
            text = read_text_file(str(ocr_path))

        return OCRPageResult(
            source_image=image_path,
            backend=self.name,
            blocks=[],
            raw_text=text,
        )
